---
title: "Almond Yield Function Documentation"
author: "Rachel Swick and Ryan Green"
date: "2025-04-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

```{r}
data <- read.table("data/clim.txt", header = TRUE, sep = " ")

data <- data %>% 
  mutate(tavg_c = (tmax_c + tmin_c)/2)
```

Y = 0.015Tn,2 0.0046T2
n;2 0:07P1 + 0.0043P2
1 þ 0:28
```{r}

```


```{r}
yield <- function(mintemp, precip) {
  
  data <- read.table("data/clim.txt", header = TRUE, sep = " ") %>% 
    mutate(tavg_c = (tmax_c + tmin_c)/2)
  
  mintemp <- data$tmin_c
  maxtemp <- data$tmax_c
  avgtemp <- data$tavg_c
  
  yieldmin <- -0.015 * mintemp - 0.0046(mintemp^2) - 0.07 * precip + 0.0043(precip^2) + 0.28
  yieldmax <- -0.015 * maxtemp - 0.0046(maxtemp^2) - 0.07 * precip + 0.0043(precip^2) + 0.28
  yieldavg -0.015 * avgtemp - 0.0046(avgtemp^2) - 0.07 * precip + 0.0043(precip^2) + 0.28
  
  return(result)
  }
```


```{r}
yield <- function(avgmintemp, precip) {
  
    data <- read.table("data/clim.txt", header = TRUE, sep = " ")
    
    data <- data %>%
      group_by(month, year) %>%
      summarise(mon_mintemp = mean(tmin_c, na.rm = TRUE), mon_total_precip = sum(precip)) 
    
    for (i in length(data$month)) {
      yield_anomaly_df <- data.frame()
      yield_anomaly = -0.015 * data$mon_mintemp - 0.0046((data$mon_mintemp**2)) - 0.07 * data$mon_total_precip + 0.0043((data$mon_total_precip**2)) + 0.28
      return(min(yield_anomaly))
    }
  
  
}
```

```{r}
# Read in the data from the text file
data <- read.table("data/clim.txt", header = TRUE, sep = " ")

# Load necessary package
library(dplyr)

# Group by month and year and calculate summary statistics. Also, we drop groups afterward.

data_february <- data %>%
  group_by(month, year) %>%
  filter(month == 2) %>% 
  summarise(mintemp = min(tmin_c, na.rm = TRUE)) %>% 
  ungroup()

data_january <- data %>%
  group_by(month, year) %>%
  filter(month == 1) %>% 
  summarise(total_precip = sum(precip, na.rm = TRUE)) %>% 
  ungroup()

data_clim <- left_join(x = data_january, y = data_february, by = "year")


# Compute the yield anomaly for each month using vectorized operations
data_clim <- data_clim %>%
  mutate(yield_anomaly = -0.015 * mintemp - 0.0046 * (mintemp^2) - 0.07 * total_precip + 0.0043 * (total_precip^2) + 0.28) 

summary_yield <- data_clim %>%
    summarise(
      min_yield = min(yield_anomaly, na.rm = TRUE),
      max_yield = max(yield_anomaly, na.rm = TRUE),
      mean_yield = mean(yield_anomaly, na.rm = TRUE))
  
print(summary_yield)
```

```{r}
almond_yield <- function(filename = "data/clim.txt") {
  # Read in the data
  data <- read.table(filename, header = TRUE, sep = " ")
  
  # Load necessary package
  library(dplyr)
  
  # Aggregate February data: get the minimum temp (tmin_c) for February per year
  data_february <- data %>%
    group_by(month, year) %>%
    filter(month == 2) %>% 
    summarise(mintemp = min(tmin_c, na.rm = TRUE)) %>% 
    ungroup()
  
  # Aggregate January data: sum of precipitation for January per year
  data_january <- data %>%
    group_by(month, year) %>%
    filter(month == 1) %>% 
    summarise(total_precip = sum(precip, na.rm = TRUE)) %>% 
    ungroup()
  
  # Join the January and February data by the year
  data_clim <- left_join(x = data_january, y = data_february, by = "year")
  
  # Compute the yield anomaly using the formula
  data_clim <- data_clim %>%
    mutate(yield_anomaly = -0.015 * mintemp - 0.0046 * (mintemp^2) - 0.07 * total_precip + 0.0043 * (total_precip^2) + 0.28)
  
  # Summarize the yield anomaly statistics
  summary_yield <- data_clim %>%
    summarise(
      min_yield = min(yield_anomaly, na.rm = TRUE),
      max_yield = max(yield_anomaly, na.rm = TRUE),
      mean_yield = mean(yield_anomaly, na.rm = TRUE))
  
  # Print the summary statistics
  print(summary_yield)
}

# Example usage:
almond_yield("data/clim.txt")

```


















